<?php
    require "functions.php";
    
    // Atari 800
    makeList(input_path("Atari 8bit - Applications - [ATR] (TOSEC-v2018-03-08_CM).dat"), "a800_flop_apps", "Atari 800 floppy disks (Applications)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Compilations - Applications - [ATR] (TOSEC-v2013-12-13_CM).dat"), "a800_flop_comp_apps", "Atari 800 floppy disks (Compilations - Applications)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Compilations - Demos - [ATR] (TOSEC-v2013-12-13_CM).dat"), "a800_flop_comp_demo", "Atari 800 floppy disks (Compilations - Demos)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Compilations - Educational - [ATR] (TOSEC-v2013-12-13_CM).dat"), "a800_flop_comp_edu", "Atari 800 floppy disks (Compilations - Educational)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Compilations - Games - [ATR] (TOSEC-v2012-07-18_CM).dat"), "a800_flop_comp_game", "Atari 800 floppy disks (Compilations - Games)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Demos - [ATR] (TOSEC-v2018-03-08_CM).dat"), "a800_flop_demos", "Atari 800 floppy disks (Demos)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Docs - [ATR] (TOSEC-v2013-12-13_CM).dat"), "a800_flop_docs", "Atari 800 floppy disks (Docs)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Educational - [ATR] (TOSEC-v2012-07-18_CM).dat"), "a800_flop_edu", "Atari 800 floppy disks (Educational)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Games - [ATR] (TOSEC-v2018-03-08_CM).dat"), "a800_flop_games", "Atari 800 floppy disks (Games)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Magazines - [ATR] (TOSEC-v2014-10-30_CM).dat"), "a800_flop_mags", "Atari 800 floppy disks (Magazines)", "flop", "floppy_5_25");
    makeList(input_path("Atari 8bit - Sources - [ATR] (TOSEC-v2013-12-13_CM).dat"), "a800_flop_src", "Atari 800 floppy disks (Sources)", "flop", "floppy_5_25");
    
    // Acorn BBC
    makeList(input_path("Acorn BBC - Applications - [ADL] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_apps_adl", "Acorn BBC series floppy disks (Applications - ADL)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Applications - [DSD] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_apps_dsd", "Acorn BBC series floppy disks (Applications - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Applications - [SSD] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_apps_ssd", "Acorn BBC series floppy disks (Applications - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Compilations - [ADL] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_comps_adl", "Acorn BBC series floppy disks (Compilations - ADL)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Compilations - [DSD] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_comps_dsd", "Acorn BBC series floppy disks (Compilations - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Compilations - [SSD] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_comps_ssd", "Acorn BBC series floppy disks (Compilations - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Coverdisks - [DSD] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_cover_dsd", "Acorn BBC series floppy disks (Coverdisks - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Coverdisks - [SSD] (TOSEC-v2013-10-16_CM).dat"), "bbc_flop_cover_ssd", "Acorn BBC series floppy disks (Coverdisks - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Demos - [SSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_demos", "Acorn BBC series floppy disks (Demos - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Educational - [ADL] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_edu_adl", "Acorn BBC series floppy disks (Educational - ADL)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Educational - [DSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_edu_dsd", "Acorn BBC series floppy disks (Educational - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Educational - [SSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_edu_ssd", "Acorn BBC series floppy disks (Educational - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Games - [ADL] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_games_adl", "Acorn BBC series floppy disks (Games - ADL)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Games - [DSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_games_dsd", "Acorn BBC series floppy disks (Games - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Games - [SSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_games_ssd", "Acorn BBC series floppy disks (Games - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Magazines - [ADL] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_mags_adl", "Acorn BBC series floppy disks (Magazines - ADL)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Magazines - [DSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_mags_dsd", "Acorn BBC series floppy disks (Magazines - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Magazines - [SSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_mags_ssd", "Acorn BBC series floppy disks (Magazines - SSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Multimedia - [ADL] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_multi_adl", "Acorn BBC series floppy disks (Multimedia - ADL)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Multimedia - [DSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_multi_dsd", "Acorn BBC series floppy disks (Multimedia - DSD)", "flop", "floppy_5_25");
    makeList(input_path("Acorn BBC - Multimedia - [SSD] (TOSEC-v2013-10-22_CM).dat"), "bbc_flop_multi_ssd", "Acorn BBC series floppy disks (Multimedia - SSD)", "flop", "floppy_5_25");
    
    // Amiga
    makeList(input_path("Commodore Amiga - Applications - [ADF] (TOSEC-v2021-02-04_CM).dat"), "amiga_tosec_apps", "Commodore Amiga floppy disks (Applications)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Applications - Public Domain - [ADF] (TOSEC-v2021-02-10_CM).dat"), "amiga_tosec_apps_pd", "Commodore Amiga floppy disks (Applications - Public Domain)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Compilations - Applications (TOSEC-v2020-03-02_CM).dat"), "amiga_tosec_comp_apps", "Commodore Amiga floppy disks (Compilations - Applications)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Compilations - Games (TOSEC-v2021-02-12_CM).dat"), "amiga_tosec_comp_games", "Commodore Amiga floppy disks (Compilations - Games)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Compilations - Various (TOSEC-v2020-03-02_CM).dat"), "amiga_tosec_comp_var", "Commodore Amiga floppy disks (Compilations - Various)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Coverdisks - [ADF] (TOSEC-v2021-01-22_CM).dat"), "amiga_tosec_cover", "Commodore Amiga floppy disks (Coverdisks)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Demos - Animations and Videos (TOSEC-v2021-02-11_CM).dat"), "amiga_tosec_demoav", "Commodore Amiga floppy disks (Demos - Animations & Videos)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Demos - Music (TOSEC-v2020-03-02_CM).dat"), "amiga_tosec_demomusic", "Commodore Amiga floppy disks (Demos - Music)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Demos - Packs (TOSEC-v2020-03-02_CM).dat"), "amiga_tosec_demopacks", "Commodore Amiga floppy disks (Demos - Packs)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Demos - Slideshows (TOSEC-v2021-02-04_CM).dat"), "amiga_tosec_demoslide", "Commodore Amiga floppy disks (Demos - Slideshows)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Demos - Various - [ADF] (TOSEC-v2021-02-11_CM).dat"), "amiga_tosec_demovar", "Commodore Amiga floppy disks (Demos - Various)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Diskmags (TOSEC-v2021-01-11_CM).dat"), "amiga_tosec_diskmags", "Commodore Amiga floppy disks (Diskmags)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Docs (TOSEC-v2020-03-02_CM).dat"), "amiga_tosec_docs", "Commodore Amiga floppy disks (Docs)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Educational - [ADF] (TOSEC-v2021-01-12_CM).dat"), "amiga_tosec_edu", "Commodore Amiga floppy disks (Educational)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Games - [ADF] (TOSEC-v2021-02-11_CM).dat"), "amiga_tosec_games", "Commodore Amiga floppy disks (Games)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Games - Unofficial Addons & Patches (TOSEC-v2020-05-27_CM).dat"), "amiga_tosec_games_adds", "Commodore Amiga floppy disks (Games - Unofficial Addons & Patches)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Games - Emerald Mine (TOSEC-v2020-11-07_CM).dat"), "amiga_tosec_games_em", "Commodore Amiga floppy disks (Games - Emerald Mine)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Games - Public Domain - [ADF] (TOSEC-v2021-02-11_CM).dat"), "amiga_tosec_games_pd", "Commodore Amiga floppy disks (Games - Public Domain)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Games - Save Disks (TOSEC-v2020-09-16_CM).dat"), "amiga_tosec_games_save", "Commodore Amiga floppy disks (Games - Save Disks)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Packmags (TOSEC-v2020-03-02_CM).dat"), "amiga_tosec_packmags", "Commodore Amiga floppy disks (Packmags)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Amiga Amateur Radio User Group (TOSEC-v2014-02-12_CM).dat"), "amiga_tosec_pd_aarug", "Commodore Amiga floppy disks (Public Domain - Amiga Amateur Radio User Group)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Amiga Public Domain Connection (TOSEC-v2017-07-19_CM).dat"), "amiga_tosec_pd_apdc", "Commodore Amiga floppy disks (Public Domain - Amiga Public Domain Connection)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Auge 4000 (TOSEC-v2014-07-14_CM).dat"), "amiga_tosec_pd_auge", "Commodore Amiga floppy disks (Public Domain - Auge 4000)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Bavarian (TOSEC-v2013-09-20_CM).dat"), "amiga_tosec_pd_bav", "Commodore Amiga floppy disks (Public Domain - Bavarian)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Best of Public Domain, The (TOSEC-v2017-04-22_CM).dat"), "amiga_tosec_pd_bpd", "Commodore Amiga floppy disks (Public Domain - The Best of Public Domain)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Berliner Spielekiste (TOSEC-v2020-06-23_CM).dat"), "amiga_tosec_pd_bsk", "Commodore Amiga floppy disks (Public Domain - Berliner Spielekiste)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Cactus (TOSEC-v2014-07-14_CM).dat"), "amiga_tosec_pd_cactus", "Commodore Amiga floppy disks (Public Domain - Cactus)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Camelot (TOSEC-v2020-11-07_CM).dat"), "amiga_tosec_pd_camelot", "Commodore Amiga floppy disks (Public Domain - Camelot)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Den Norske Hjemmedataklubben (TOSEC-v2017-04-09_CM).dat"), "amiga_tosec_pd_dnh", "Commodore Amiga floppy disks (Public Domain - Den Norske Hjemmedataklubben)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Franz PD (TOSEC-v2019-12-16_CM).dat"), "amiga_tosec_pd_franz", "Commodore Amiga floppy disks (Public Domain - Franz PD)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Fred Fish (TOSEC-v2020-04-12_CM).dat"), "amiga_tosec_pd_fish", "Commodore Amiga floppy disks (Public Domain - Fred Fish)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Memphis Amiga Group (TOSEC-v2016-08-13_CM).dat"), "amiga_tosec_pd_mag", "Commodore Amiga floppy disks (Public Domain - Memphis Amiga Group)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - MegaDisc (TOSEC-v2016-09-25_CM).dat"), "amiga_tosec_pd_mega", "Commodore Amiga floppy disks (Public Domain - MegaDisc)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Nordlicht Spiele (TOSEC-v2018-03-05_CM).dat"), "amiga_tosec_pd_nord", "Commodore Amiga floppy disks (Public Domain - Nordlicht Spiele)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - New Zealand Amiga Users Group (TOSEC-v2011-11-01_CM).dat"), "amiga_tosec_pd_nzaug", "Commodore Amiga floppy disks (Public Domain - New Zealand Amiga Users Group)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Panorama (TOSEC-v2016-07-10_CM).dat"), "amiga_tosec_pd_pan", "Commodore Amiga floppy disks (Public Domain - Panorama)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Scope (TOSEC-v2013-07-24_CM).dat"), "amiga_tosec_pd_scope", "Commodore Amiga floppy disks (Public Domain - Scope)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Software of the Month Club (SOMC) (TOSEC-v2011-11-01_CM).dat"), "amiga_tosec_pd_somc", "Commodore Amiga floppy disks (Public Domain - Software of the Month Club)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Taifun (TOSEC-v2019-11-28_CM).dat"), "amiga_tosec_pd_taifun", "Commodore Amiga floppy disks (Public Domain - Taifun)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Tampa Bay Amiga Group (TOSEC-v2013-07-24_CM).dat"), "amiga_tosec_pd_tbag", "Commodore Amiga floppy disks (Public Domain - Tampa Bay Amiga Group)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - TOGA (TOSEC-v2021-02-11_CM).dat"), "amiga_tosec_pd_toga", "Commodore Amiga floppy disks (Public Domain - TOGA)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Topik (TOSEC-v2011-11-01_CM).dat"), "amiga_tosec_pd_topik", "Commodore Amiga floppy disks (Public Domain - Topik)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - TSWF (TOSEC-v2018-08-20_CM).dat"), "amiga_tosec_pd_tswf", "Commodore Amiga floppy disks (Public Domain - TSWF)", "flop", "floppy_3_5");
    makeList(input_path("Commodore Amiga - Collections - Various (TOSEC-v2017-11-07_CM).dat"), "amiga_tosec_pd_var", "Commodore Amiga floppy disks (Public Domain - Various)", "flop", "floppy_3_5");
    
    // C64 (5.25)
    makeList(input_path("Commodore C64 - Animations - [D64] (TOSEC-v2020-01-20_CM).dat"), "c64_flop_anim", "Commodore 64 floppy disks (Animations)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Applications - [D64] (TOSEC-v2021-01-12_CM).dat"), "c64_flop_app_d64", "Commodore 64 floppy disks (Applications - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Applications - [D71] (TOSEC-v2021-02-11_CM).dat"), "c64_flop_app_d71", "Commodore 64 floppy disks (Applications - D71)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Applications - [G64] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_app_g64", "Commodore 64 floppy disks (Applications - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Applications - Test Disks - [D64] (TOSEC-v2020-10-23_CM).dat"), "c64_flop_app_test_d64", "Commodore 64 floppy disks (Applications - Test Disks - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Applications - Test Disks - [D71] (TOSEC-v2018-10-18_CM).dat"), "c64_flop_app_test_d71", "Commodore 64 floppy disks (Applications - Test Disks - D71)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Applications - Test Disks - [G64] (TOSEC-v2019-09-21_CM).dat"), "c64_flop_app_test_g64", "Commodore 64 floppy disks (Applications - Test Disks - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Blast from the Past (TOSEC-v2017-08-22_CM).dat"), "c64_flop_col_bftp", "Commodore 64 floppy disks (Collections - Blast from the Past)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - BugJam (TOSEC-v2019-09-21_CM).dat"), "c64_flop_col_bugjam", "Commodore 64 floppy disks (Collections - BugJam)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - C64CD'96 (TOSEC-v2019-12-15_CM).dat"), "c64_flop_col_cd96", "Commodore 64 floppy disks (Collections - C64CD'96)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Derbyshire Ram - [D64] (TOSEC-v2019-02-17_CM).dat"), "c64_flop_col_dram_d64", "Commodore 64 floppy disks (Collections - Derbyshire Ram - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Derbyshire Ram - [G64] (TOSEC-v2019-02-17_CM).dat"), "c64_flop_col_dram_g64", "Commodore 64 floppy disks (Collections - Derbyshire Ram - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Dotson (TOSEC-v2019-02-20_CM).dat"), "c64_flop_col_dotson", "Commodore 64 floppy disks (Collections - Dotson)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Earthshaker (TOSEC-v2020-07-02_CM).dat"), "c64_flop_col_eshaker", "Commodore 64 floppy disks (Collections - Earthshaker)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Einstein (TOSEC-v2019-02-17_CM).dat"), "c64_flop_col_einstein", "Commodore 64 floppy disks (Collections - Einstein)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Fairlight (TOSEC-v2017-08-22_CM).dat"), "c64_flop_col_fairlight", "Commodore 64 floppy disks (Collections - Fairlight)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Great White North (TOSEC-v2019-02-24_CM).dat"), "c64_flop_col_gwn", "Commodore 64 floppy disks (Collections - Great White North)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - High Voltage (TOSEC-v2019-02-20_CM).dat"), "c64_flop_col_hvoltage", "Commodore 64 floppy disks (Collections - High Voltage)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Hornet (TOSEC-v2017-08-22_CM).dat"), "c64_flop_col_hornet", "Commodore 64 floppy disks (Collections - Hornet)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Jazzcat (TOSEC-v2019-09-21_CM).dat"), "c64_flop_col_jazzcat", "Commodore 64 floppy disks (Collections - Jazzcat)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Manik (TOSEC-v2019-02-17_CM).dat"), "c64_flop_col_manik", "Commodore 64 floppy disks (Collections - Manik)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Oxyron (TOSEC-v2019-12-15_CM).dat"), "c64_flop_col_oxyron", "Commodore 64 floppy disks (Collections - Oxyron)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Tadpole (TOSEC-v2017-08-22_CM).dat"), "c64_flop_col_tadpole", "Commodore 64 floppy disks (Collections - Tadpole)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Collections - Watties (TOSEC-v2017-08-22_CM).dat"), "c64_flop_col_watties", "Commodore 64 floppy disks (Collections - Watties)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Demos - [D64] (TOSEC-v2020-09-23_CM).dat"), "c64_flop_comp_demo_d64", "Commodore 64 floppy disks (Compilations - Demos - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Demos - [G64] (TOSEC-v2018-11-25_CM).dat"), "c64_flop_comp_demo_g64", "Commodore 64 floppy disks (Compilations - Demos - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Diskmags - [D64] (TOSEC-v2020-04-28_CM).dat"), "c64_flop_comp_mag", "Commodore 64 floppy disks (Compilations - Diskmags)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Educational (TOSEC-v2018-12-16_CM).dat"), "c64_flop_comp_edu", "Commodore 64 floppy disks (Compilations - Educational)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Games - [D64] (TOSEC-v2020-09-20_CM).dat"), "c64_flop_comp_game_d64", "Commodore 64 floppy disks (Compilations - Games - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Music - [D64] (TOSEC-v2020-10-23_CM).dat"), "c64_flop_comp_music", "Commodore 64 floppy disks (Compilations - Music)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Compilations - Various - [D64] (TOSEC-v2020-08-08_CM).dat"), "c64_flop_comp_var", "Commodore 64 floppy disks (Compilations - Various)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Coverdisks - [D64] (TOSEC-v2020-10-25_CM).dat"), "c64_flop_cover_d64", "Commodore 64 floppy disks (Coverdisks - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Cracktros - [D64] (TOSEC-v2020-12-21_CM).dat"), "c64_flop_crack", "Commodore 64 floppy disks (Cracktros)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Demos - [D64] (TOSEC-v2021-02-11_CM).dat"), "c64_flop_demo_d64", "Commodore 64 floppy disks (Demos - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Demos - [D71] (TOSEC-v2020-10-10_CM).dat"), "c64_flop_demo_d71", "Commodore 64 floppy disks (Demos - D71)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Demos - [G64] (TOSEC-v2018-11-25_CM).dat"), "c64_flop_demo_g64", "Commodore 64 floppy disks (Demos - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Diskmags - Commercial - [D64] (TOSEC-v2021-02-06_CM).dat"), "c64_flop_mag_com_d64", "Commodore 64 floppy disks (Diskmags - Commercial - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Diskmags - Commercial - [G64] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_mag_com_g64", "Commodore 64 floppy disks (Diskmags - Commercial - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Diskmags - Scene - [D64] (TOSEC-v2021-02-09_CM).dat"), "c64_flop_mag_scene_d64", "Commodore 64 floppy disks (Diskmags - Scene - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Diskmags - Scene - [D71] (TOSEC-v2012-06-24_CM).dat"), "c64_flop_mag_scene_d71", "Commodore 64 floppy disks (Diskmags - Scene - D71)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Diskmags - Scene - [G64] (TOSEC-v2019-01-05_CM).dat"), "c64_flop_mag_scene_g64", "Commodore 64 floppy disks (Diskmags - Scene - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Docs - [D64] (TOSEC-v2020-09-23_CM).dat"), "c64_flop_doc_d64", "Commodore 64 floppy disks (Docs - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Docs - [G64] (TOSEC-v2018-12-16_CM).dat"), "c64_flop_doc_g64", "Commodore 64 floppy disks (Docs - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Educational - [D64] (TOSEC-v2021-01-12_CM).dat"), "c64_flop_edu_d64", "Commodore 64 floppy disks (Educational - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Educational - [G64] (TOSEC-v2021-01-12_CM).dat"), "c64_flop_edu_g64", "Commodore 64 floppy disks (Educational - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - [D64] (TOSEC-v2021-02-11_CM).dat"), "c64_flop_game_d64", "Commodore 64 floppy disks (Games - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - [D71] (TOSEC-v2020-04-05_CM).dat"), "c64_flop_game_d71", "Commodore 64 floppy disks (Games - D71)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - [G64] (TOSEC-v2021-01-12_CM).dat"), "c64_flop_game_g64", "Commodore 64 floppy disks (Games - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - 3DCK - [D64] (TOSEC-v2021-01-30_CM).dat"), "c64_flop_game_3dck", "Commodore 64 floppy disks (Games - 3DCK)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - ACS - [D64] (TOSEC-v2020-01-19_CM).dat"), "c64_flop_game_acs", "Commodore 64 floppy disks (Games - ACS)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - Boulder Dash - [D64] (TOSEC-v2020-12-21_CM).dat"), "c64_flop_game_bdash_d64", "Commodore 64 floppy disks (Games - Boulder Dash - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - Boulder Dash - [G64] (TOSEC-v2018-08-19_CM).dat"), "c64_flop_game_bdash_g64", "Commodore 64 floppy disks (Games - Boulder Dash - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - GKGM - [D64] (TOSEC-v2020-12-21_CM).dat"), "c64_flop_game_gkgm", "Commodore 64 floppy disks (Games - GKGM)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - PCS - [D64] (TOSEC-v2020-12-21_CM).dat"), "c64_flop_game_pcs", "Commodore 64 floppy disks (Games - PCS)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - Previews - [D64] (TOSEC-v2021-01-30_CM).dat"), "c64_flop_game_prv_d64", "Commodore 64 floppy disks (Games - Previews - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - Previews - [G64] (TOSEC-v2018-11-11_CM).dat"), "c64_flop_game_prv_g64", "Commodore 64 floppy disks (Games - Previews - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - SEUCK - [D64] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_game_seuck_d64", "Commodore 64 floppy disks (Games - SEUCK - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Games - SEUCK - [G64] (TOSEC-v2018-02-21_CM).dat"), "c64_flop_game_seuck_g64", "Commodore 64 floppy disks (Games - SEUCK - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - GEOS - [D64] (TOSEC-v2020-10-23_CM).dat"), "c64_flop_geos", "Commodore 64 floppy disks (GEOS)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Graphics - [D64] (TOSEC-v2021-01-30_CM).dat"), "c64_flop_gfx_d64", "Commodore 64 floppy disks (Graphics - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Music - [D64] (TOSEC-v2021-02-11_CM).dat"), "c64_flop_music_d64", "Commodore 64 floppy disks (Music - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Music - [D71] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_music_d71", "Commodore 64 floppy disks (Music - D71)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Music - [G64] (TOSEC-v2021-02-09_CM).dat"), "c64_flop_music_g64", "Commodore 64 floppy disks (Music - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Operating Systems - [D64] (TOSEC-v2021-01-01_CM).dat"), "c64_flop_os", "Commodore 64 floppy disks (Operating Systems)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Public Domain - [D64] (TOSEC-v2019-04-23_CM).dat"), "c64_flop_pd_d64", "Commodore 64 floppy disks (Public Domain - D64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Public Domain - [G64] (TOSEC-v2014-02-02_CM).dat"), "c64_flop_pd_g64", "Commodore 64 floppy disks (Public Domain - G64)", "flop", "floppy_5_25");
    makeList(input_path("Commodore C64 - Sources (TOSEC-v2014-02-01_CM).dat"), "c64_flop_src", "Commodore 64 floppy disks (Sources)", "flop", "floppy_5_25");
    
    // C64 (3.5)
    makeList(input_path("Commodore C64 - Applications - [D81] (TOSEC-v2021-02-09_CM).dat"), "c64_flop_app_d81", "Commodore 64 floppy disks (Applications - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Compilations - Games - [D81] (TOSEC-v2018-08-19_CM).dat"), "c64_flop_comp_game_d81", "Commodore 64 floppy disks (Compilations - Games - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Coverdisks - [D81] (TOSEC-v2013-09-16_CM).dat"), "c64_flop_cover_d81", "Commodore 64 floppy disks (Coverdisks - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Demos - [D81] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_demo_d81", "Commodore 64 floppy disks (Demos - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Diskmags - Commercial - [D81] (TOSEC-v2020-01-20_CM).dat"), "c64_flop_mag_com_d81", "Commodore 64 floppy disks (Diskmags - Commercial - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Diskmags - Scene - [D81] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_mag_scene_d81", "Commodore 64 floppy disks (Diskmags - Scene - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Educational - [D81] (TOSEC-v2019-12-13_CM).dat"), "c64_flop_edu_d81", "Commodore 64 floppy disks (Educational - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Games - [D81] (TOSEC-v2020-11-03_CM).dat"), "c64_flop_game_d81", "Commodore 64 floppy disks (Games - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Games - Previews - [D81] (TOSEC-v2018-12-16_CM).dat"), "c64_flop_game_prv_d81", "Commodore 64 floppy disks (Games - Previews - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Graphics - [D81] (TOSEC-v2018-01-03_CM).dat"), "c64_flop_gfx_d81", "Commodore 64 floppy disks (Graphics - D81)", "flop", "floppy_3_5");
    makeList(input_path("Commodore C64 - Music - [D81] (TOSEC-v2021-01-27_CM).dat"), "c64_flop_music_d81", "Commodore 64 floppy disks (Music - D81)", "flop", "floppy_3_5");
    
    // Atari ST
    makeList(input_path("Atari ST - Compilations - Applications (TOSEC-v2015-05-07_CM).dat"), "st_comp_apps", "Atari ST floppy disks (Compilations - Applications)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Compilations - Demos (TOSEC-v2015-05-07_CM).dat"), "st_comp_demo", "Atari ST floppy disks (Compilations - Demos)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Compilations - Educational (TOSEC-v2013-12-13_CM).dat"), "st_comp_edu", "Atari ST floppy disks (Compilations - Educational)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Compilations - Games - [ST] (TOSEC-v2015-05-07_CM).dat"), "st_comp_game", "Atari ST floppy disks (Compilations - Games)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Compilations - Games - [STX] (TOSEC-v2015-05-07_CM).dat"), "st_comp_game_stx", "Atari ST floppy disks (Compilations - Games - STX)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Collections - FaST Club (TOSEC-v2013-12-13_CM).dat"), "st_fast", "Atari ST floppy disks (FaST Club)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Collections - Floppyshop (TOSEC-v2011-03-07_CM).dat"), "st_flopshop", "Atari ST floppy disks (Floppyshop)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Games - [ST] (TOSEC-v2020-07-12_CM).dat"), "st_games", "Atari ST floppy disks (Games)", "flop", "floppy_3_5");
    makeList(input_path("Atari ST - Games - [STX] (TOSEC-v2018-03-18_CM).dat"), "st_games_stx", "Atari ST floppy disks (Games - STX)", "flop", "floppy_3_5");
    
    // TI-99
    makeList(input_path("Texas Instruments TI-99 4A - Various (TOSEC-v2014-06-06_CM).dat"), "ti99_flop", "Texas Instruments TI-99/4A floppy disks", "flop", "floppy_5_25");
?>
